sudo: false

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

#language: cpp
#compiler:
#  - clang
#  - gcc
#env:
#  - CXX=clang
#  - CXX=gcc

addons:
  apt:
    packages:
    - protobuf-compiler

before_install:
  - composer self-update

install:

before_script:
  - uname -a
  - cat /etc/lsb-release
  - g++ --version || echo "no g++ found"
  - clang++ --version || echo "no clang++ found"
  - make --version || echo "no make found"
  - automake --version || echo "no automake found"
  - autoconf --version || echo "no autoconf found"
  - php --version || echo "no php found"
  - protoc --version || echo "no protoc found"

script:
  - ./autogen.sh && ./configure
  - make test

cache:
  directories:
    - tests/vendor
    - $HOME/.composer/cache