sudo: false

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

#language: cpp
#compiler:
#  - clang
#  - gcc
#env:
#  - CXX=clang
#  - CXX=gcc

addons:
  apt:
    packages:
    # proto3 isn't in packages, so we build it ourselves below
    # - libprotobuf-dev
    # - protobuf-compiler

    # TODO If we want to support c++11 uncomment the following
    # # http://stackoverflow.com/a/30925448/88646
    # sources:
    # - ubuntu-toolchain-r-test
    # packages:
    # - gcc-4.8
    # - g++-4.8
    # - clang

before_install:
  - ./install-protobuf.sh
  - export LD_LIBRARY_PATH="$HOME/lib:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="$HOME/lib:$LIBRARY_PATH"
  - export PATH="$HOME/bin:$PATH"
  - export PKG_CONFIG_PATH="$HOME/lib/pkgconfig:$PKG_CONFIG_PATH"
  - export C_INCLUDE_PATH="$HOME/include:$C_INCLUDE_PATH"
  - export CPLUS_INCLUDE_PATH="$HOME/include:$CPLUS_INCLUDE_PATH"

  - composer self-update

install:
  # TODO If we want to support c++11 uncomment the following
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - uname -a
  - cat /etc/lsb-release
  - g++ --version || echo "no g++ found"
  - clang++ --version || echo "no clang++ found"
  - make --version || echo "no make found"
  - automake --version || echo "no automake found"
  - autoconf --version || echo "no autoconf found"
  - php --version || echo "no php found"
  - protoc --version || echo "no protoc found"

script:
  - ./autogen.sh && ./configure
  - make test

cache:
  apt: true
  ccache: true
  directories:
    - tests/vendor
    - $HOME/.composer/cache
